### PR TITLE
Add automatically displayName to functional components

### PR DESCRIPTION
**Pull request by Joozty**
This helps to debug errors in production build and also helps to distinguish children by type,e.g. `children.type.displayName = 'SelectOption'`

### CODE REVIEW

**Comment by Joozty** [comment]
Well it's about finding correct chidlren. Imagine something like this:

```
<Select>
    <Select.Option>1</Select.Option>
    <Select.Option>2</Select.Option>
    <Select.Option>3</Select.Option>
    <Select.Option>Search all results</Select.Option>
    <Select.Value>
        <div>Eleement on top of input when not focused</div>
     </Select.Option>
</Select>
```

You may want to find all options and get props from them, then you want to find Section.Value component and check if there is only one of its type (if not throw exception). We use this approach in [Dashboard Table]() too.  I don't see anything wrong with it...  :) 


Note the example doesn't reflect the reality. I probably won't use <Select.Value/> (at least not in the first version)

**Comment by viktor-yakubiv** [comment]
> I probably won't use <Select.Value/> (at least not in the first version)

Please, don't 😄

**Comment by viktor-yakubiv** [comment]
You may enforce it, this is where you go. However, I would let the user pass whatever he/she/they want to but unexpected behaviour is also on their shoulders.

In my example, if you have

```jsx
<Select value="a value">
  <Menu.Item value="a value">A value</Menu.Item>
</Select>
```

it may behave correctly but it would not work with the filtering you want.

**Comment by Joozty** [comment]
The rationale behind it is to allow custom styling and reuse this component in the dashboard. Something like (not needed at the time, it was more just to provide you example):

```
    <Select.Value>
        <bold>Org name</bold>
        <span>Repo name</div>
     </Select.Value>
```

**Comment by Joozty** [comment]
Your example is just fine. So it will be just one condition more...

**Pull request merged**
