### PR TITLE
Style disabled TextFields

### PR DESCRIPTION
**Pull request by Joozty**
Closes https://github.com/oacore/design/issues/178

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
It's a good start. However, the read-only should not be 'disallowed'

**Comment by Joozty** [comment]
Why? I see both of them the same.

**Comment by viktor-yakubiv** [comment]
Read-only allows to select and copy text but does not allow to change. `Disabled` means that the user must not interact with. It should be clear.

**Comment by Joozty** [comment]
Interesting. Thanks for the explanation.

**Pull request merged**
